### PR TITLE
Add "committer commented" column

### PR DESCRIPTION
**Pull request by JoshRosen**
This patch adds an "Committer Commented" column to the PRTableView which shows the timestamp of the most recent comment from any Spark committer.

### CODE REVIEW

**Comment by JoshRosen** [comment]
This change is currently deployed in case you want to test it out.

**Comment by ajbozarth** [comment]
I like the addition but it's awkward visually with each word in "Updated by Committer" wrapping to its own line. Maybe change it to "Committer Updated" or "Committer Commented" so it only wraps to two line like other headers?

Also The Stale PR tab isn't filling in the column, I think `refreshStalePrs` needs to be updated to match changes to `refreshPrs` in `AppManager.js`

**Comment by jkbradley** [comment]
I like "Committer Commented" since it's really about comments.  (The PR author could be a committer, but code updates are not counted in this column.)

I'm not one to review Javascript, but apart from the bug @ajbozarth pointed out, this LGTM when I use it on the site.  Thank you!

**Comment by ajbozarth** [comment]
Outside my previous comment the code LGTM as well

**Comment by JoshRosen** [comment]
Thanks for reviewing. I've updated this to incorporate your feedback.

**Comment by ajbozarth** [comment]
LGTM

**Comment by ajbozarth** [comment]
So I just noticed an odd behavior that this update made more obvious, you can currently see it on the main page. If there is both a pr with a long word in its title and another with a long user name and it's making the table wider than the page width causing a horizontal scroll.

**Comment by JoshRosen** [comment]
Ah, that's unfortunate. It would be neat if we could truncate long titles in the frontend using Javascript with the `overflow: ellipsis` CSS option. Feel free to give it a try and submit a PR and I'll review.

**Pull request merged**
