### PR TITLE
Add K8s to Project components

### LINKED ISSUE #83: Add K8s to project components
We have the other cluster managers there and I suspect the K8s folks would find it useful (I know I would). cc @ifilonenko

### PR DESCRIPTION
**Pull request by ifilonenko**
Adding k8s as project component.

Closes #83.

### CODE REVIEW

**Comment by ifilonenko** [comment]
@holdenk and others for review and testing

**Comment by JoshRosen** [comment]
I deployed this for testing; see results at https://spark-prs.appspot.com/#kubernetes

If that looks good to you then I'll merge.

**Comment by ifilonenko** [comment]
LGTM @JoshRosen :) please merge

**Comment by JoshRosen** [comment]
Merged. Thanks @ifilonenko!

**Pull request merged**
